"""
Django settings for core_exchange project.

Generated by 'django-admin startproject' using Django 5.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-0l$ssxse&c$9u%vgjj=)e5fda@*_+xi6yu7d@(901(29z12r(3'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['SupReg.pythonanywhere.com', 'www.SupReg.pythonanywhere.com', '127.0.0.1', 'fullfinanzas.pythonanywhere.com', 'www.fullfinanzas.pythonanywhere.com']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'usuarios',
    'django_celery_beat',
    
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core_exchange.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core_exchange.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'usuarios.Usuario'


LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/usuarios/dashboard/'  
LOGOUT_REDIRECT_URL = '/login/'


MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# CELERY
CELERY_BROKER_URL = 'redis://localhost:6379/0'
CELERY_RESULT_BACKEND = 'redis://localhost:6379/1'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'



SITE_URL = "http://localhost:8000"       
EMPRESA_NOMBRE = "Full Finanzas"
EMPRESA_CUIT = "30-00000000-0"
EMPRESA_DOMICILIO = "Av. Cordoba 123, CABA"
SUPPORT_CONTACTO = "soporte@fullfinanzas.com / +54 11 5555-0000"
PSAV_LEYENDA = "Francisco Molina - Proveedor de Servicios de Activos Virtuales (PSAV) inscripto bajo el N°16 de la fecha 13 de mayo de 2025 del Registro PSAV – Personas Humanas, en el Registro de Proveedores de Servicios de Activos Virtuales de CNV. Este registro es a los fines del control como Sujeto Obligado ante la Unidad de Información Financiera (UIF) y de todo otro ente regulador facultado a tal efecto, en el marco de sus competencias, y no implica licencia ni supervisión por parte de la COMISIÓN NACIONAL DE VALORES sobre la actividad realizada por el PSAV"  


# COMISION

SWAP_FEE_BPS = 100  
SPREAD_BPS_USDT = 200  
SPREAD_BPS_USD  = 200  

#EMAIL SOPORTE
EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"  # dev
DEFAULT_FROM_EMAIL = "soporte@fullfinanzas.com"
SOPORTE_TO = ["soporte@fullfinanzas.com"]  # destinatarios del equipo


#tiempo restablecimiento contraseña
PASSWORD_RESET_TIMEOUT = 60 * 60 * 24  # 24 hs 

#Email verificacion 
 # email_backend
DEFAULT_FROM_EMAIL = "Full Finanzas <no-reply@fullfinanzas.com>"

#produccion
# EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
# EMAIL_HOST = "smtp.sendgrid.net"   # o tu proveedor
# EMAIL_PORT = 587
# EMAIL_HOST_USER = "apikey"         # SendGrid example
# EMAIL_HOST_PASSWORD = "SG.xxxxxx"  # tu API key
# EMAIL_USE_TLS = True
# DEFAULT_FROM_EMAIL = "Full Finanzas <no-reply@fullfinanzas.com>"



TYC_VERSION = "2025"


# --------------- seguridad--------------


# SECURE_SSL_REDIRECT = True
# SESSION_COOKIE_SECURE = True
# CSRF_COOKIE_SECURE = True
# SECURE_HSTS_SECONDS = 31536000
# SECURE_HSTS_INCLUDE_SUBDOMAINS = True
# SECURE_HSTS_PRELOAD = True
# CSRF_TRUSTED_ORIGINS = ["https://tu-dominio.com", "https://www.tu-dominio.com"]
# SECURE_REFERRER_POLICY = "strict-origin-when-cross-origin" #usar este si necesitas que integradores vean el origen
# SECURE_REFERRER_POLICY = "same-origin" #mas estricto
# SECURE_CONTENT_TYPE_NOSNIFF = True
# X_FRAME_OPTIONS = "DENY"


# CSP (django-csp)
#INSTALLED_APPS += ["csp"]
#CSP_DEFAULT_SRC = ("'self'",)
#CSP_SCRIPT_SRC  = ("'self'", "cdn.jsdelivr.net")  # Chart.js
#CSP_STYLE_SRC   = ("'self'", "'unsafe-inline'")
#CSP_IMG_SRC     = ("'self'", "data:")
#CSP_CONNECT_SRC = ("'self'",)

# INSTALLED_APPS += ["whitenoise.runserver_nostatic"]
# MIDDLEWARE.insert(1, "whitenoise.middleware.WhiteNoiseMiddleware")

AUTHENTICATION_BACKENDS = [
    'usuarios.auth_backends.EmailOrUsernameBackend',
    'django.contrib.auth.backends.ModelBackend',
]