# Generated by Django 5.2.3 on 2025-06-13 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='dni_grente',
            new_name='dni_frente',
        ),
    ]
