# Generated by Django 5.2.3 on 2025-06-23 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_rename_dni_grente_usuario_dni_frente'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='saldo_usd',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
