# Generated by Django 5.2.3 on 2025-06-23 23:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_depositoars'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('deposito', 'Depósito'), ('retiro', 'Retiro'), ('compra', 'Compra'), ('ajuste', 'Ajuste manual')], max_length=20)),
                ('moneda', models.CharField(choices=[('ARS', 'Pesos ARS'), ('USDT', 'USDT'), ('USD', 'USD')], max_length=10)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=20)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
