# Generated by Django 5.2.3 on 2025-07-03 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_movimiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moneda', models.CharField(choices=[('USDT', 'USDT'), ('USD', 'USD')], max_length=10)),
                ('compra', models.DecimalField(decimal_places=2, max_digits=20)),
                ('venta', models.DecimalField(decimal_places=2, max_digits=20)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
