# Generated by Django 5.2.3 on 2025-07-07 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_retiroars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retiroars',
            name='cbu',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
