# Generated by Django 5.2.3 on 2025-07-25 18:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_movimiento_admin_responsable_movimiento_saldo_antes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimiento',
            name='codigo',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
