# Generated by Django 5.2.3 on 2025-08-05 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0012_retirocrypto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='retirocrypto',
            old_name='fecha',
            new_name='fecha_solicitud',
        ),
        migrations.AddField(
            model_name='retirocrypto',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
