# Generated by Django 5.2.3 on 2025-08-14 21:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0013_rename_fecha_retirocrypto_fecha_solicitud_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepositoUSDT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=20)),
                ('red', models.CharField(choices=[('TRC20', 'TRC20'), ('ERC20', 'ERC20'), ('BEP20', 'BEP20'), ('SOL', 'Solana')], max_length=10)),
                ('txid', models.CharField(max_length=200)),
                ('comprobante', models.ImageField(upload_to='comprobantes_usdt/')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
