# Generated by Django 5.2.3 on 2025-09-04 21:20

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0014_depositousdt'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='doc_nro',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='usuario',
            name='doc_tipo',
            field=models.CharField(default='DNI', max_length=8),
        ),
        migrations.AddField(
            model_name='usuario',
            name='domicilio',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='usuario',
            name='nacionalidad',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='usuario',
            name='telefono',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.CreateModel(
            name='BoletoOperacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('compra_ars_usdt', 'Compra USDT con ARS'), ('compra_ars_usd', 'Compra USD con ARS'), ('venta_usdt_ars', 'Venta USDT por ARS'), ('venta_usd_ars', 'Venta USD por ARS'), ('swap_usd_usdt', 'Swap USD→USDT'), ('swap_usdt_usd', 'Swap USDT→USD'), ('deposito_ars', 'Depósito ARS'), ('deposito_usdt', 'Depósito USDT'), ('retiro_ars', 'Retiro ARS'), ('retiro_usdt', 'Retiro USDT'), ('retiro_usd', 'Retiro USD')], max_length=32)),
                ('numero', models.CharField(max_length=40, unique=True)),
                ('fecha_emision', models.DateTimeField(default=django.utils.timezone.now)),
                ('snapshot', models.JSONField()),
                ('pdf', models.FileField(upload_to='boletos/')),
                ('pdf_sha256', models.CharField(max_length=64)),
                ('verificacion_code', models.CharField(max_length=64, unique=True)),
                ('anulado', models.BooleanField(default=False)),
                ('red', models.CharField(blank=True, max_length=32)),
                ('wallet_origen', models.CharField(blank=True, max_length=255)),
                ('wallet_destino', models.CharField(blank=True, max_length=255)),
                ('txid', models.CharField(blank=True, max_length=255)),
                ('movimiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.movimiento')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_emision'],
            },
        ),
    ]
