# Generated by Django 5.2.3 on 2025-09-16 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0015_usuario_doc_nro_usuario_doc_tipo_usuario_domicilio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Localidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=140)),
                ('slug', models.SlugField(blank=True, max_length=160)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iso2', models.CharField(max_length=2, unique=True)),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Paises',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='usuario',
            name='calle',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='usuario',
            name='codigo_postal',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='usuario',
            name='depto',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='usuario',
            name='estado_civil',
            field=models.CharField(blank=True, choices=[('SOLTERO', 'Soltero/a'), ('CASADO', 'Casado/a'), ('DIVORCIADO', 'Divorciado/a'), ('VIUDO', 'Viudo/a'), ('CONVIVIENTE', 'Unión convivencial'), ('OTRO', 'Otro')], max_length=20),
        ),
        migrations.AddField(
            model_name='usuario',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='lugar_nacimiento',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='usuario',
            name='numero_calle',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='usuario',
            name='persona_tipo',
            field=models.CharField(choices=[('FISICA', 'Persona física'), ('JURIDICA', 'Persona jurídica')], default='FISICA', max_length=10),
        ),
        migrations.AddField(
            model_name='usuario',
            name='piso',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='usuario',
            name='sexo',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('X', 'No binario / X'), ('ND', 'Prefiero no decir')], max_length=10),
        ),
        migrations.AddField(
            model_name='usuario',
            name='tyc_aceptado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuario',
            name='tyc_aceptado_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='tyc_version',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='usuario',
            name='localidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='usuarios.localidad'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='pais',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='usuarios.pais'),
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, max_length=140)),
                ('georef_id', models.CharField(blank=True, max_length=10)),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provincias', to='usuarios.pais')),
            ],
            options={
                'ordering': ['nombre'],
                'unique_together': {('pais', 'nombre')},
            },
        ),
        migrations.AddField(
            model_name='localidad',
            name='provincia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='localidades', to='usuarios.provincia'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='provincia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='usuarios.provincia'),
        ),
        migrations.AlterUniqueTogether(
            name='localidad',
            unique_together={('provincia', 'nombre')},
        ),
    ]
