# Generated by Django 5.2.3 on 2025-09-24 15:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0016_localidad_pais_usuario_calle_usuario_codigo_postal_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('asunto', models.CharField(max_length=150)),
                ('categoria', models.CharField(choices=[('cuenta', 'Cuenta / Perfil'), ('operaciones', 'Operaciones (comprar/vender/swap)'), ('verificacion', 'Verificación KYC'), ('pagos', 'Depósitos / Retiros'), ('otro', 'Otro')], default='otro', max_length=32)),
                ('prioridad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta')], default='media', max_length=16)),
                ('mensaje', models.TextField()),
                ('adjunto', models.FileField(blank=True, null=True, upload_to='tickets/')),
                ('estado', models.CharField(default='abierto', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-creado_en',),
            },
        ),
    ]
