# Generated by Django 5.2.3 on 2025-10-06 19:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0017_supportticket'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuentaExchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Exchange', max_length=50, unique=True)),
                ('saldo_ars', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('saldo_usdt', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('saldo_usd', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
            ],
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='margin_bps',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='ref_compra',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='ref_venta',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True),
        ),
        migrations.CreateModel(
            name='ApunteExchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('tipo', models.CharField(choices=[('comision_swap', 'Comisión SWAP'), ('spread_compra', 'Spread en COMPRA'), ('spread_venta', 'Spread en VENTA'), ('ajuste', 'Ajuste contable')], max_length=30)),
                ('moneda', models.CharField(choices=[('ARS', 'ARS'), ('USDT', 'USDT'), ('USD', 'USD')], max_length=10)),
                ('monto_moneda', models.DecimalField(decimal_places=6, max_digits=20)),
                ('monto_ars', models.DecimalField(decimal_places=2, max_digits=20)),
                ('ref_movimiento', models.CharField(blank=True, max_length=64)),
                ('detalle', models.TextField(blank=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
