# Generated by Django 5.2.3 on 2025-10-06 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0018_cuentaexchange_cotizacion_margin_bps_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apunteexchange',
            options={'ordering': ['-fecha']},
        ),
        migrations.AddField(
            model_name='apunteexchange',
            name='applied_price',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='apunteexchange',
            name='categoria',
            field=models.CharField(choices=[('comision_swap', 'Comisión SWAP'), ('spread_compra', 'Spread en COMPRA'), ('spread_venta', 'Spread en VENTA'), ('ingreso_deposito', 'Ingreso por depósito'), ('pago_retiro', 'Pago de retiro'), ('ajuste', 'Ajuste contable')], default='ajuste', max_length=40),
        ),
        migrations.AddField(
            model_name='apunteexchange',
            name='extra',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='apunteexchange',
            name='movimiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='apuntes_exchange', to='usuarios.movimiento'),
        ),
        migrations.AddField(
            model_name='apunteexchange',
            name='ref_price',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='apunteexchange',
            name='tipo',
            field=models.CharField(choices=[('comision_swap', 'Comisión SWAP'), ('spread_compra', 'Spread en COMPRA'), ('spread_venta', 'Spread en VENTA'), ('ajuste', 'Ajuste contable'), ('ingreso', 'Ingreso'), ('egreso', 'Egreso')], default='ingreso', max_length=30),
        ),
    ]
