# Generated by Django 5.2.3 on 2025-10-07 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0019_alter_apunteexchange_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apunteexchange',
            name='categoria',
            field=models.CharField(choices=[('spread_compra', 'Spread en COMPRA'), ('spread_venta', 'Spread en VENTA'), ('fee_swap', 'Comisión de SWAP'), ('entrada', 'Entrada (depósito acreditado)'), ('salida', 'Salida (retiro enviado)'), ('ajuste', 'Ajuste contable')], default='ajuste', max_length=40),
        ),
    ]
