# Generated by Django 5.2.3 on 2025-11-12 22:21

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0021_usuario_email_confirm_sent_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singleton', models.BooleanField(default=True, editable=False, unique=True)),
                ('swap_fee_bps', models.PositiveIntegerField(default=100, help_text='Comisión del swap en basis points (100 bps = 1%).', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5000)])),
                ('spread_bps_usdt', models.PositiveIntegerField(default=200, help_text='Spread aplicado a USDT en bps.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5000)])),
                ('spread_bps_usd', models.PositiveIntegerField(default=200, help_text='Spread aplicado a USD en bps.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5000)])),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuración de Exchange',
                'verbose_name_plural': 'Configuración de Exchange',
            },
        ),
    ]
