# Generated by Django 5.2.3 on 2026-02-18 15:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0022_exchangeconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='margin_bps_compra',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='margin_bps_venta',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exchangeconfig',
            name='spread_bps_usd_compra',
            field=models.PositiveIntegerField(default=200, help_text='Spread aplicado a USD (lado COMPRA) en bps.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5000)]),
        ),
        migrations.AddField(
            model_name='exchangeconfig',
            name='spread_bps_usd_venta',
            field=models.PositiveIntegerField(default=200, help_text='Spread aplicado a USD (lado VENTA) en bps.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5000)]),
        ),
        migrations.AddField(
            model_name='exchangeconfig',
            name='spread_bps_usdt_compra',
            field=models.PositiveIntegerField(default=200, help_text='Spread aplicado a USDT (lado COMPRA) en bps.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5000)]),
        ),
        migrations.AddField(
            model_name='exchangeconfig',
            name='spread_bps_usdt_venta',
            field=models.PositiveIntegerField(default=200, help_text='Spread aplicado a USDT (lado VENTA) en bps.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5000)]),
        ),
    ]
