# Generated by Django 5.2.3 on 2026-02-24 04:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0023_cotizacion_margin_bps_compra_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangeconfig',
            name='spread_bps_usd_compra',
            field=models.IntegerField(default=200, help_text='Spread aplicado a USD (lado COMPRA) en bps.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5000)]),
        ),
        migrations.AlterField(
            model_name='exchangeconfig',
            name='spread_bps_usd_venta',
            field=models.IntegerField(default=200, help_text='Spread aplicado a USD (lado VENTA) en bps.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5000)]),
        ),
        migrations.AlterField(
            model_name='exchangeconfig',
            name='spread_bps_usdt_compra',
            field=models.IntegerField(default=200, help_text='Spread aplicado a USDT (lado COMPRA) en bps.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5000)]),
        ),
        migrations.AlterField(
            model_name='exchangeconfig',
            name='spread_bps_usdt_venta',
            field=models.IntegerField(default=200, help_text='Spread aplicado a USDT (lado VENTA) en bps.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5000)]),
        ),
    ]
