# Generated by Django 5.2.3 on 2026-02-24 05:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0024_alter_exchangeconfig_spread_bps_usd_compra_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangeconfig',
            name='spread_bps_usd',
            field=models.IntegerField(default=200, help_text='Spread aplicado a USD en bps.', validators=[django.core.validators.MinValueValidator(-5000), django.core.validators.MaxValueValidator(5000)]),
        ),
        migrations.AlterField(
            model_name='exchangeconfig',
            name='spread_bps_usd_compra',
            field=models.IntegerField(default=200, help_text='Spread aplicado a USD (lado COMPRA) en bps.', validators=[django.core.validators.MinValueValidator(-5000), django.core.validators.MaxValueValidator(5000)]),
        ),
        migrations.AlterField(
            model_name='exchangeconfig',
            name='spread_bps_usd_venta',
            field=models.IntegerField(default=200, help_text='Spread aplicado a USD (lado VENTA) en bps.', validators=[django.core.validators.MinValueValidator(-5000), django.core.validators.MaxValueValidator(5000)]),
        ),
        migrations.AlterField(
            model_name='exchangeconfig',
            name='spread_bps_usdt',
            field=models.IntegerField(default=200, help_text='Spread aplicado a USDT en bps.', validators=[django.core.validators.MinValueValidator(-5000), django.core.validators.MaxValueValidator(5000)]),
        ),
        migrations.AlterField(
            model_name='exchangeconfig',
            name='spread_bps_usdt_compra',
            field=models.IntegerField(default=200, help_text='Spread aplicado a USDT (lado COMPRA) en bps.', validators=[django.core.validators.MinValueValidator(-5000), django.core.validators.MaxValueValidator(5000)]),
        ),
        migrations.AlterField(
            model_name='exchangeconfig',
            name='spread_bps_usdt_venta',
            field=models.IntegerField(default=200, help_text='Spread aplicado a USDT (lado VENTA) en bps.', validators=[django.core.validators.MinValueValidator(-5000), django.core.validators.MaxValueValidator(5000)]),
        ),
        migrations.AlterField(
            model_name='exchangeconfig',
            name='swap_fee_bps',
            field=models.PositiveIntegerField(default=100, help_text='Comisión del swap en basis points (100 bps = 1%).', validators=[django.core.validators.MinValueValidator(-5000), django.core.validators.MaxValueValidator(5000)]),
        ),
    ]
